Test against a matrix of golang versions and update various actions versions (#34)
- The v4 folder tests now generate an ephemeral ECDSA key pair, extract
a PKCS#11 CKA_EC_POINT from that key pair, and pass the existing
TestSignECDSA implementation.
- Added a pre-configured softhsm directory with key material from
`v4/testdata/`.
- Several unused variables were removed from test files.
- The main readme has been updated.
- Fixes TestSignECDSA for newer versions of golang due to
```
--- FAIL: TestSignECDSA (0.00s)
panic: crypto/elliptic: attempted operation on invalid point [recovered]
	panic: crypto/elliptic: attempted operation on invalid point
```

### Background 
Starting in Golang 1.18, crypto/elliptic: IsOnCurve began returning true
for invalid field elements (elliptic curve points X and Y).
[[1]](https://github.com/golang/go/issues/50974)

Relatedly in Golang 1.19, crypto/elliptic: IsOnCurve was updated to
explicitly panic when operating on invalid field elements.
[[2]](https://github.com/golang/go/issues/50975)

However, this should have still been failing on Golang 1.18 (even though
it wasn't!!) because the points (1,1) are invalid. I believe what
happened here was
[[3]](https://github.com/golang/go/issues/51059#issuecomment-1034191363):
> [...] started returning random points when asked to operate on invalid
points in Go 1.18, like at the line you linked. (We decided to make it
an explicit panic in Go 1.19 to avoid painful debugging sessions like
the one we caused you, sorry, but it was too late for Go 1.18.